"""added Entries to swagger

Revision ID: 45ed1fbccb49
Revises: 06e949bc3bae
Create Date: 2024-10-16 16:19:25.947664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ed1fbccb49'
down_revision = '06e949bc3bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id_entry', sa.Integer(), nullable=False),
    sa.Column('cover_img', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=15), nullable=False),
    sa.Column('source_file', sa.String(length=100), nullable=True),
    sa.Column('github_link', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_entry')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    # ### end Alembic commands ###
