"""entries on delete cascade

Revision ID: 51bb9964d71f
Revises: 6ecaa7ba76df
Create Date: 2024-10-17 15:15:51.389304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bb9964d71f'
down_revision = '6ecaa7ba76df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_constraint('entries_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['id_user'], ['id_user'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('entries_ibfk_1', 'users', ['id_user'], ['id_user'])

    # ### end Alembic commands ###
