"""empty message

Revision ID: 6ecaa7ba76df
Revises: 45ed1fbccb49
Create Date: 2024-10-16 16:22:50.728748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ecaa7ba76df'
down_revision = '45ed1fbccb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id_entry', sa.Integer(), nullable=False),
    sa.Column('cover_img', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=15), nullable=False),
    sa.Column('source_file', sa.String(length=100), nullable=True),
    sa.Column('github_link', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_entry')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=sa.BLOB(),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('member_since',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('member_since',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('profile_pic',
               existing_type=sa.String(length=300),
               type_=sa.BLOB(),
               existing_nullable=True)

    op.drop_table('entries')
    # ### end Alembic commands ###
